In [1]:
#Creating a class and object
class Dog:
    attr1 = "mammal"
    def __init__(self, name):
        self.name = name
Rodger = Dog("Rodger")
Tommy = Dog("Tommy")

print("Rodger is a {}".format(Rodger.__class__.attr1))
print("Tommy is also a {}".format(Tommy.__class__.attr1))

print("My name is {}".format(Rodger.name))
print("My name is {}".format(Tommy.name))

Rodger is a mammal
Tommy is also a mammal
My name is Rodger
My name is Tommy


In [3]:
class Employee:
    company_name = 'ABC Company'
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary
    def show(self):
        print('Employee:', self.name, self.salary, self.company_name)
emp1 = Employee("Harry", 12000)
emp1.show()
emp2 = Employee("Emma", 10000)
emp2.show()


Employee: Harry 12000 ABC Company
Employee: Emma 10000 ABC Company


In [4]:
#INHERITANCE
class Person(object):

    def __init__(self, name, idnumber):
        self.name = name
        self.idnumber = idnumber

    def display(self):
        print(self.name)
        print(self.idnumber)

    def details(self):
        print("My name is {}".format(self.name))
        print("IdNumber: {}".format(self.idnumber))

class Employee(Person):
    def __init__(self, name, idnumber, salary, post):
        self.salary = salary
        self.post = post
        Person.__init__(self, name, idnumber)

    def details(self):
        print("My name is {}".format(self.name))
        print("IdNumber: {}".format(self.idnumber))
        print("Post: {}".format(self.post))

a = Employee('Rahul', 886012, 200000, "Intern")
a.display()
a.details()

Rahul
886012
My name is Rahul
IdNumber: 886012
Post: Intern


In [5]:
#polymorphism
class Bird:
    def intro(self):
        print("There are many types of birds.")

    def flight(self):
        print("Most of the birds can fly but some cannot.")

class sparrow(Bird):
    def flight(self):
        print("Sparrows can fly.")
class ostrich(Bird):
    def flight(self):
        print("Ostriches cannot fly.")
obj_bird = Bird()
obj_spr = sparrow()
obj_ost = ostrich()
obj_bird.intro()
obj_bird.flight()
obj_spr.intro()
obj_spr.flight()
obj_ost.intro()
obj_ost.flight()

There are many types of birds.
Most of the birds can fly but some cannot.
There are many types of birds.
Sparrows can fly.
There are many types of birds.
Ostriches cannot fly.


In [7]:
#Encapsulation
class Base:
    def __init__(self):
        self.a = "helloooo"
        self.__c = "hello"

class Derived(Base):
    def __init__(self):
        Base.__init__(self)
        print("Calling private member of base class: ")
        print(self.__c)
obj1 = Base()
print(obj1.a)

helloooo


In [8]:
#Abstraction
class Rectangle:
    def __init__(self, length, width):
        self.__length = length
        self.__width = width

    def area(self):
        return self.__length * self.__width

    def perimeter(self):
        return 2 * (self.__length + self.__width)

rect = Rectangle(5, 3)
print(f"Area: {rect.area()}")
print(f"Perimeter: {rect.perimeter()}")

Area: 15
Perimeter: 16


In [9]:
#create a numpy array with 6 random integers from 10 to 30
import numpy as np
arr = np.random.randint(10, 30, 6)
print(arr)


[20 13 16 12 12 28]


In [22]:
#Create a numpy array of size 10 x 5 with random values and extract the first five rows into variable
import numpy as np
arr = np.random.rand(10, 5)
print(arr)
first_five_rows = arr[:5]
print(first_five_rows)


[[0.04291836 0.64251241 0.6428391  0.19019792 0.51877912]
 [0.60346876 0.86150658 0.17585115 0.72627956 0.52125646]
 [0.36044607 0.89735178 0.9143344  0.78239601 0.43077856]
 [0.08220908 0.61575865 0.23890548 0.21758147 0.89490891]
 [0.56218333 0.78932168 0.62154294 0.65386478 0.81205976]
 [0.93858336 0.93325032 0.19774866 0.74442794 0.84404002]
 [0.89462178 0.47459957 0.47784981 0.66987185 0.92041082]
 [0.02489608 0.7501915  0.61971663 0.03627741 0.95249194]
 [0.81098924 0.75604689 0.3617845  0.82687584 0.71077608]
 [0.06102195 0.8696964  0.74591167 0.35908889 0.48740437]]
[[0.04291836 0.64251241 0.6428391  0.19019792 0.51877912]
 [0.60346876 0.86150658 0.17585115 0.72627956 0.52125646]
 [0.36044607 0.89735178 0.9143344  0.78239601 0.43077856]
 [0.08220908 0.61575865 0.23890548 0.21758147 0.89490891]
 [0.56218333 0.78932168 0.62154294 0.65386478 0.81205976]]


In [17]:
#create a numpy array of size 5x5 with random values and find the maximum and minimum in them
import numpy as np
arr = np.random.rand(5, 5)
print(arr)
min,max = arr.min(),arr.max()
print("highest=",max,"lowest=",min)

[[0.21521109 0.96632899 0.54165909 0.45039874 0.74773363]
 [0.52316692 0.85283071 0.67664119 0.27498234 0.32265184]
 [0.03723833 0.06959895 0.0022219  0.93942787 0.61331111]
 [0.54845874 0.98848399 0.41866991 0.0805934  0.72503255]
 [0.89772251 0.21053808 0.36776572 0.64185794 0.91455979]]
highest= 0.9884839918562478 lowest= 0.002221902914073204


In [23]:
#create a numpy array which has numbers shuffled between 1 to 10
import numpy as np
x = np.arange(1,11)
print(x)
np.random.shuffle(x)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  5  6  8  9  7 10  3  4  2]
